[package]
name = "crudexample"
version = "0.1.0"
authors = ["guohao 2019091604028"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
